<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class HotelSeeder extends Seeder
{
    public function run()
    {
        DB::table('hotels')->insert([
            [
                'destination_id' => 2,
                'name' => 'Halal Paradise Hotel',
                'address' => '123 Main Street',
                'city' => 'Kuala Lumpur',
                'country' => 'Malaysia',
                'price_per_night' => 150.00,
                'halal_certified' => true,
                'rating' => 4.5,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'destination_id' => 1,
                'name' => 'Medina Suites',
                'address' => '456 Medina Road',
                'city' => 'Istanbul',
                'country' => 'Turkey',
                'price_per_night' => 200.00,
                'halal_certified' => true,
                'rating' => 4.8,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'destination_id' => 1,
                'name' => 'Makka Luxury Inn',
                'address' => '789 Makka Blvd',
                'city' => 'Istanbul',
                'country' => 'Turkey',
                'price_per_night' => 250.00,
                'halal_certified' => true,
                'rating' => 4.9,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'destination_id' => 2,
                'name' => 'Keyel Halal Stay',
                'address' => '101 Keyel Lane',
                'city' => 'Kuala Lumpur',
                'country' => 'Malaysia',
                'price_per_night' => 120.00,
                'halal_certified' => true,
                'rating' => 4.3,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'destination_id' => 1,
                'name' => 'Istanbul Heritage Hotel',
                'address' => '202 Istanbul Avenue',
                'city' => 'Istanbul',
                'country' => 'Turkey',
                'price_per_night' => 180.00,
                'halal_certified' => true,
                'rating' => 4.7,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'destination_id' => 3,
                'name' => 'Marrakech Halal Resort',
                'address' => '303 Marrakech Creek',
                'city' => 'Marrakech',
                'country' => 'Morocco',
                'price_per_night' => 300.00,
                'halal_certified' => true,
                'rating' => 4.6,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'destination_id' => 3,
                'name' => 'Amman Halal Inn',
                'address' => '404 Amman Boulevard',
                'city' => 'Marrakech',
                'country' => 'Morocco',
                'price_per_night' => 130.00,
                'halal_certified' => true,
                'rating' => 4.2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'destination_id' => 3,
                'name' => 'Marrakech Halal Stay',
                'address' => '505 Nile Street',
                'city' => 'Marrakech',
                'country' => 'Morocco',
                'price_per_night' => 110.00,
                'halal_certified' => true,
                'rating' => 4.1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'destination_id' => 2,
                'name' => 'Penang Halal Paradise',
                'address' => '606 KL Road',
                'city' => 'Kuala Lumpur',
                'country' => 'Malaysia',
                'price_per_night' => 90.00,
                'halal_certified' => true,
                'rating' => 4.4,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'destination_id' => 3,
                'name' => 'KL Halal Hotel',
                'address' => '707 Orchard Road',
                'city' => 'Kuala Lumpur',
                'country' => 'Malaysia',
                'price_per_night' => 170.00,
                'halal_certified' => true,
                'rating' => 4.3,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);
    }
}
