<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class HotelSeeder extends Seeder
{
    public function run()
    {
        DB::table('hotels')->insert([
            [
                'destination_id' => 2,
                'name' => 'Times Square Suite',
                'address' => '1, Jalan Imbi, 55100',
                'city' => 'Kuala Lumpur',
                'country' => 'Malaysia',
                'price_per_night' => 150.00,
                'halal_certified' => true,
                'rating' => 5.0,
                'created_at' => now(),
                'updated_at' => now(),
                'booking_url' =>'http://tiny.cc/bko5001',
            ],
            [
                'destination_id' => 1,
                'name' => 'On Historical Peninsula K aya R oyal Hotel',
                'address' => 'Şakirefendi Çeşmesi Sokağı, Fatih, 34130',
                'city' => 'Istanbul',
                'country' => 'Turkey',
                'price_per_night' => 200.00,
                'halal_certified' => true,
                'rating' => 4.0,
                'created_at' => now(),
                'updated_at' => now(),
                'booking_url' =>'http://tiny.cc/nko5001',
            ],
            [
                'destination_id' => 1,
                'name' => 'Star of İstanbul Residence',
                'address' => '56 Süleyman Nazif Sokak, Sisli, 34371',
                'city' => 'Istanbul',
                'country' => 'Turkey',
                'price_per_night' => 250.00,
                'halal_certified' => true,
                'rating' => 4.6,
                'created_at' => now(),
                'updated_at' => now(),
                'booking_url' =>'http://tiny.cc/tko5001',
            ],
            [
                'destination_id' => 2,
                'name' => 'Anggun Residence KLCC',
                'address' => 'Jalan Medan Tuanku, Chow Kit, 50250',
                'city' => 'Kuala Lumpur',
                'country' => 'Malaysia',
                'price_per_night' => 120.00,
                'halal_certified' => true,
                'rating' => 4.0,
                'created_at' => now(),
                'updated_at' => now(),
                'booking_url' =>'http://tiny.cc/yko5001',
            ],
            [
                'destination_id' => 1,
                'name' => 'Novel Hotel',
                'address' => 'Harikzedeler Sokak No: 15 - Laleli, Fatih, 34134',
                'city' => 'Istanbul',
                'country' => 'Turkey',
                'price_per_night' => 180.00,
                'halal_certified' => true,
                'rating' => 4.9,
                'created_at' => now(),
                'updated_at' => now(),
                'booking_url' =>'http://tiny.cc/0lo5001',
            ],
            [
                'destination_id' => 3,
                'name' => 'Dar Al-Famila',
                'address' => 'Sidi bensliman El jazouli derb sidi Masaoud Nr. 1, Medina, 40000',
                'city' => 'Marrakech',
                'country' => 'Morocco',
                'price_per_night' => 300.00,
                'halal_certified' => true,
                'rating' => 4.4,
                'created_at' => now(),
                'updated_at' => now(),
                'booking_url' =>'http://tiny.cc/5lo5001',
            ],
            [
                'destination_id' => 3,
                'name' => 'Riad Catalina',
                'address' => '21 Derb Abdellah Ben Hssain, Medina, 40000',
                'city' => 'Marrakech',
                'country' => 'Morocco',
                'price_per_night' => 130.00,
                'halal_certified' => true,
                'rating' => 4.0,
                'created_at' => now(),
                'updated_at' => now(),
                'booking_url' =>'http://tiny.cc/alo5001',
            ],
            [
                'destination_id' => 3,
                'name' => 'Riad Mokha Mokha & Spa',
                'address' => 'Riad El Moukha N°26 Arset My Moussa Sghira 26, Medina, 40000',
                'city' => 'Marrakech',
                'country' => 'Morocco',
                'price_per_night' => 110.00,
                'halal_certified' => true,
                'rating' => 4.4,
                'created_at' => now(),
                'updated_at' => now(),
                'booking_url' =>'http://tiny.cc/1ko5001',
            ],
            [
                'destination_id' => 2,
                'name' => 'Imperial KLCC Residence',
                'address' => '15, Jalan Kia Peng, 50450',
                'city' => 'Kuala Lumpur',
                'country' => 'Malaysia',
                'price_per_night' => 90.00,
                'halal_certified' => true,
                'rating' => 5.0,
                'created_at' => now(),
                'updated_at' => now(),
                'booking_url' =>'http://tiny.cc/dlo500',
            ],
            [
                'destination_id' => 3,
                'name' => 'Hotel Le Gallia',
                'address' => '30, Rue de la Recette - Riad Mokha, Medina, 40008',
                'city' => 'Marrakech',
                'country' => 'Morocco',
                'price_per_night' => 170.00,
                'halal_certified' => true,
                'rating' => 4.6,
                'created_at' => now(),
                'updated_at' => now(),
                'booking_url' =>'http://tiny.cc/hlo5001',
            ],
        ]);
    }
}
