<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class RestaurantSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('restaurants')->insert([
            // Restaurants for Istanbul
            [
                'destination_id' => 1, // Istanbul
                'name' => 'Istanbul Halal Bites',
                'address' => '123 Sultanahmet St.',
                'city' => 'Istanbul',
                'country' => 'Turkey',
                'halal_certified' => true,
                'rating' => 4.5,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'destination_id' => 1,
                'name' => 'Bosphorus Grill',
                'address' => '456 Bosphorus Blvd.',
                'city' => 'Istanbul',
                'country' => 'Turkey',
                'halal_certified' => false,
                'rating' => 4.2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'destination_id' => 1,
                'name' => 'Golden Horn Cafe',
                'address' => '789 Galata Tower Rd.',
                'city' => 'Istanbul',
                'country' => 'Turkey',
                'halal_certified' => true,
                'rating' => 4.8,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'destination_id' => 1,
                'name' => 'Topkapi Feast',
                'address' => '321 Hagia Sophia Blvd.',
                'city' => 'Istanbul',
                'country' => 'Turkey',
                'halal_certified' => false,
                'rating' => 4.6,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'destination_id' => 1,
                'name' => 'Sultan’s Delight',
                'address' => '654 Blue Mosque St.',
                'city' => 'Istanbul',
                'country' => 'Turkey',
                'halal_certified' => true,
                'rating' => 4.7,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'destination_id' => 1,
                'name' => 'Galata Bistro',
                'address' => '987 Bosphorus View Rd.',
                'city' => 'Istanbul',
                'country' => 'Turkey',
                'halal_certified' => true,
                'rating' => 4.4,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'destination_id' => 1,
                'name' => 'Pera Kitchen',
                'address' => '147 Taksim Square Ln.',
                'city' => 'Istanbul',
                'country' => 'Turkey',
                'halal_certified' => false,
                'rating' => 4.3,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'destination_id' => 1,
                'name' => 'Dolmabahce Dining',
                'address' => '258 Bosphorus Corner Rd.',
                'city' => 'Istanbul',
                'country' => 'Turkey',
                'halal_certified' => true,
                'rating' => 4.6,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'destination_id' => 1,
                'name' => 'Ottoman Grill',
                'address' => '369 Spice Bazaar Blvd.',
                'city' => 'Istanbul',
                'country' => 'Turkey',
                'halal_certified' => true,
                'rating' => 4.9,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'destination_id' => 1,
                'name' => 'Halal Istanbul',
                'address' => '741 Grand Bazaar St.',
                'city' => 'Istanbul',
                'country' => 'Turkey',
                'halal_certified' => true,
                'rating' => 4.5,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // Restaurants for Kuala Lumpur
            [
                'destination_id' => 2, // Kuala Lumpur
                'name' => 'KL Halal Feast',
                'address' => '789 Bukit Bintang Rd.',
                'city' => 'Kuala Lumpur',
                'country' => 'Malaysia',
                'halal_certified' => true,
                'rating' => 4.8,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'destination_id' => 2,
                'name' => 'Malaysian Delights',
                'address' => '222 Twin Tower Ln.',
                'city' => 'Kuala Lumpur',
                'country' => 'Malaysia',
                'halal_certified' => false,
                'rating' => 4.3,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'destination_id' => 2,
                'name' => 'Nasi Lemak Corner',
                'address' => '123 Merdeka Square Rd.',
                'city' => 'Kuala Lumpur',
                'country' => 'Malaysia',
                'halal_certified' => true,
                'rating' => 4.7,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'destination_id' => 2,
                'name' => 'Petronas Food Court',
                'address' => '456 KLCC St.',
                'city' => 'Kuala Lumpur',
                'country' => 'Malaysia',
                'halal_certified' => true,
                'rating' => 4.6,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'destination_id' => 2,
                'name' => 'Roti Canai Haven',
                'address' => '789 Jalan Alor Rd.',
                'city' => 'Kuala Lumpur',
                'country' => 'Malaysia',
                'halal_certified' => true,
                'rating' => 4.9,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'destination_id' => 2,
                'name' => 'Satay Delight',
                'address' => '333 Kajang Satay St.',
                'city' => 'Kuala Lumpur',
                'country' => 'Malaysia',
                'halal_certified' => true,
                'rating' => 4.7,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'destination_id' => 2,
                'name' => 'Char Kuey Teow Palace',
                'address' => '888 Penang St.',
                'city' => 'Kuala Lumpur',
                'country' => 'Malaysia',
                'halal_certified' => false,
                'rating' => 4.4,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'destination_id' => 2,
                'name' => 'Banana Leaf Heaven',
                'address' => '111 Little India Ln.',
                'city' => 'Kuala Lumpur',
                'country' => 'Malaysia',
                'halal_certified' => true,
                'rating' => 4.5,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'destination_id' => 2,
                'name' => 'Durian Paradise',
                'address' => '999 Durian St.',
                'city' => 'Kuala Lumpur',
                'country' => 'Malaysia',
                'halal_certified' => true,
                'rating' => 4.8,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'destination_id' => 2,
                'name' => 'Pandan Bliss',
                'address' => '444 Pandan Rd.',
                'city' => 'Kuala Lumpur',
                'country' => 'Malaysia',
                'halal_certified' => false,
                'rating' => 4.6,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // Restaurants for Marrakech
            [
                'destination_id' => 3, // Marrakech
                'name' => 'Halal Marrakech',
                'address' => '123 Medina St.',
                'city' => 'Marrakech',
                'country' => 'Morocco',
                'halal_certified' => true,
                'rating' => 4.7,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'destination_id' => 3,
                'name' => 'Moroccan Tajine Palace',
                'address' => '456 Kasbah Rd.',
                'city' => 'Marrakech',
                'country' => 'Morocco',
                'halal_certified' => false,
                'rating' => 4.4,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'destination_id' => 3,
                'name' => 'Argan Bistro',
                'address' => '789 Jardin Majorelle Ln.',
                'city' => 'Marrakech',
                'country' => 'Morocco',
                'halal_certified' => true,
                'rating' => 4.8,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'destination_id' => 3,
                'name' => 'Souk Cafe',
                'address' => '321 Souk St.',
                'city' => 'Marrakech',
                'country' => 'Morocco',
                'halal_certified' => true,
                'rating' => 4.5,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'destination_id' => 3,
                'name' => 'Koutoubia Delights',
                'address' => '654 Koutoubia Blvd.',
                'city' => 'Marrakech',
                'country' => 'Morocco',
                'halal_certified' => true,
                'rating' => 4.7,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'destination_id' => 3,
                'name' => 'Djemaa el-Fna Cuisine',
                'address' => '987 Djemaa St.',
                'city' => 'Marrakech',
                'country' => 'Morocco',
                'halal_certified' => true,
                'rating' => 4.9,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'destination_id' => 3,
                'name' => 'Atlas Mountain Grill',
                'address' => '147 Atlas Rd.',
                'city' => 'Marrakech',
                'country' => 'Morocco',
                'halal_certified' => true,
                'rating' => 4.6,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'destination_id' => 3,
                'name' => 'Couscous Haven',
                'address' => '258 Couscous Ln.',
                'city' => 'Marrakech',
                'country' => 'Morocco',
                'halal_certified' => true,
                'rating' => 4.8,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'destination_id' => 3,
                'name' => 'Mint Tea Bliss',
                'address' => '369 Mint Blvd.',
                'city' => 'Marrakech',
                'country' => 'Morocco',
                'halal_certified' => false,
                'rating' => 4.3,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'destination_id' => 3,
                'name' => 'Halal Medina',
                'address' => '741 Medina Rd.',
                'city' => 'Marrakech',
                'country' => 'Morocco',
                'halal_certified' => true,
                'rating' => 4.5,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);
    }
}
